name: neovortex
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - httpx>=0.23.0
  - aiohttp>=3.8.0
  - pydantic>=1.10.0
  - oauthlib>=3.2.0
  - requests-oauthlib>=1.3.0
  - pyjwt>=2.6.0
  - redis-py>=4.5.0
  - prometheus-client>=0.16.0
  - websockets>=10.4
  - click>=8.1.0
  - pytest>=7.2.0
  - pytest-asyncio>=0.26.0
  - cryptography>=42.0.0
  - boto3>=1.28.0
  - botocore>=1.31.0
  - sentry-sdk>=1.30.0
  - elasticsearch>=8.0.0
  - jsonschema>=4.17.0
  - xmltodict>=0.13.0
  - graphql-core>=3.2.0
  - openapi-core>=0.18.0
  - pyyaml>=6.0.0
  - hvac>=1.0.0
  - pip:
      - flake8>=6.0.0