name: Python Package using Conda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.9'
        auto-update-conda: true
    - name: Install dependencies
      run: |
        conda install pip
        pip install flake8 pytest pytest-asyncio
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        pytest tests/ --verbose